### ISSUE TITLE
Auto-generation produces bad results for "extension from mime" routine

### ISSUE THREAD

**Issue by TPETb** [elephox-dev/mimey#1]
https://github.com/elephox-dev/mimey/blob/develop/dist/MimeType.php#L1384

this means that `->getExtension('audio/mpeg');` produces `.mpga`. There's same problem w/ jpg and maybe more. mpga is simply pretty noticeable since it is typically ignored or unrecognized by contemporary apps and frameworks without extra config. This can sometimes be a very big problem with mobile devices.

Original lib had fine-tuned pick for extensions. E.g. https://github.com/ralouphie/mimey/blob/develop/mime.types.php#L4001-L4014

Do you think there's a way to restore such priority without too much work involved?

**Comment by ricardoboss** [comment]
Yes! First of all, thanks for bringing this up. Exceptions like these are why https://github.com/elephox-dev/mimey/blob/develop/data/mime.types.custom exists. Please try to create a PR to add this exception.

If you need help, don't hesitate to ask for it 😃

**Comment by ricardoboss** [comment]
One examle: https://github.com/elephox-dev/mimey/commit/ff9f95ee5805e50095056b409557eb438af4e621#diff-2f022ff53e23cc11b1e68b24038d87cc5aee2d277f393cbcbabb086344b5f82b

Please make sure the format is correct as it won't work with malformed mime.types files.

**Comment by ricardoboss** [comment]
I just noticed there already exists an entry in `mime.types.custom` for `audio/mpeg`...

Maybe there is a bug when applying the custom mappings. I will look into it.

**Comment by ricardoboss** [comment]
@TPETb Can you update to `4.0.5` and see if the issue persists?

7e8ef36969e9c36843ab7a70c5f6f5edf35a30fa should fix this.

**Comment by ricardoboss** [comment]
I'll assume the issue is fixed.
